import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Js App Router",
  description: "Generated by next Js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <h1>This is Header</h1>
        </header>
        {children}
        <footer>
          <h1>This is Footer</h1>
        </footer>
      </body>
    </html>
  );
}
