import SideBar from "../components/shared/SideBar";

export const metadata = {
  title: "Dashboard Layout",
  description: "Generated by next Js",
};

const DashboardLayout = ({ children }) => {
  return (
    <div className="flex">
      <SideBar />
      <div className="w-full">{children}</div>
    </div>
  );
};

export default DashboardLayout;
